[install]
bat.pkg-path = "bat"
emacs.pkg-path = "emacs-macport"
eza.pkg-path = "eza"
fish.pkg-path = "fish"
gawk.pkg-path = "gawk"
gitu.pkg-path = "gitu"
gnused.pkg-path = "gnused"
hyperfine.pkg-path = "hyperfine"
jq.pkg-path = "jq"
just.pkg-path = "just"
mtr.pkg-path = "mtr"
neovim.pkg-path = "neovim"
skim.pkg-path = "skim"
socat.pkg-path = "socat"
starship.pkg-path = "starship"
stow.pkg-path = "stow"
tokei.pkg-path = "tokei"
tree.pkg-path = "tree"
watch.pkg-path = "watch"
xh.pkg-path = "xh"
zoxide.pkg-path = "zoxide"
