# -*- mode: ruby -*-

# brew tap Homebrew/bundle
# brew bundle --file=~/dotfiles/Brewfile

tap 'homebrew/cask-fonts'

brew 'bettertouchtool'
brew 'cloc'
brew 'emacs-plus'
brew 'git'
brew 'gnu-sed'
brew 'gnupg'
brew 'htop'
brew 'iftop'
brew 'ispell'
berw 'iterm2'
brew 'font-inconsolata'
brew 'font-fira-code'
brew 'jq'
brew 'mtr'
brew 'neomutt'
brew 'nmap'
brew 'offlineimap'
brew 'python3'
brew 'python@2'
brew 'ripgrep'
brew 'rlwrap'
brew 'ruby'
brew 'stow'
brew 'telegram-desktop'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'watch'
brew 'weechat'
brew 'wget'
brew 'zsh'
