(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (winum which-key web-mode use-package toc-org pip-requirements paradox org-mime live-py-mode intero hy-mode hl-todo highlight-numbers helm-make git-timemachine git-link flycheck-haskell evil-surround evil-matchit dumb-jump dockerfile-mode company-anaconda auto-yasnippet anaconda-mode aggressive-indent adaptive-wrap ace-link hydra cider sesman clojure-mode tern iedit smartparens evil flycheck flyspell-correct haskell-mode company yasnippet avy markdown-mode alert projectile org-plus-contrib magit git-commit ghub with-editor helm helm-core gruvbox-theme yapfify yaml-mode xterm-color ws-butler web-beautify volatile-highlights vi-tilde-fringe uuidgen undo-tree treepy tagedit spinner spaceline slim-mode shell-pop scss-mode sass-mode restclient-helm restart-emacs rainbow-delimiters queue pyvenv pytest pyenv-mode py-isort pug-mode popwin persp-mode pcre2el parent-mode orgit org-projectile org-present org-pomodoro org-download open-junk-file ob-restclient ob-http ob-elixir nginx-mode multi-term move-text mmm-mode markdown-toc magit-popup magit-gh-pulls macrostep lorem-ipsum log4e livid-mode linum-relative link-hint let-alist json-mode js2-refactor js-doc indent-guide hungry-delete htmlize hlint-refactor hindent highlight-parentheses highlight-indentation helm-themes helm-swoop helm-pydoc helm-projectile helm-mode-manager helm-hoogle helm-gitignore helm-flx helm-descbinds helm-css-scss helm-company helm-c-yasnippet helm-ag haskell-snippets graphql goto-chg google-translate golden-ratio gnuplot gntp github-search github-clone github-browse-file gitconfig-mode gitattributes-mode git-messenger gist gh-md fuzzy flyspell-correct-helm flycheck-pos-tip flycheck-mix flycheck-credo fill-column-indicator eyebrowse expand-region exec-path-from-shell evil-visualstar evil-visual-mark-mode evil-unimpaired evil-search-highlight-persist evil-numbers evil-magit evil-lisp-state evil-indent-plus evil-iedit-state evil-exchange evil-escape evil-ediff evil-commentary evil-cleverparens evil-args evil-anzu eshell-z eshell-prompt-extras esh-help elisp-slime-nav diminish define-word cython-mode company-web company-tern company-statistics company-restclient company-ghci company-ghc company-cabal column-enforce-mode coffee-mode cmm-mode clojure-snippets clj-refactor clean-aindent-mode cider-eval-sexp-fu bind-key autothemer auto-highlight-symbol auto-dictionary auto-compile apib-mode alchemist ace-window))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
