"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = """
$status$cmd_duration$directory$character$custom"""

[status]
disabled = false
format = '<[$status]($style)> '

[cmd_duration]
min_time = 1_000  # ms
format = '\(took [$duration]($style)\) '

[directory]
truncate_to_repo = true
style = 'bold purple'

[character]
success_symbol = 'λ'
error_symbol = 'λ'

[custom.vterm_marker]
format = '$output'
command = 'printf "\e]51;A$(whoami)@$(hostname):$(pwd)\e\\"'
description = 'vterm prompt marker'
when = '[[ "$INSIDE_EMACS" == "vterm" ]]'
style = ''
