[user]
name = "Robin Schroer"
email = "git@sulami.xyz"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[ui]
default-command = "status"
diff-formatter = ":git"
pager = [ "delta", "--pager", "less -FRX" ]

[aliases]
l = [ "log" ]
ll = [ "log", "-r", "all()" ]
lf = [ "log", "-r", "::@" ]
sh = [ "show" ]

[templates]
git_push_bookmark = '"sulami/push-" ++ change_id.short()'
draft_commit_description = '''
concat(
  coalesce(description, default_commit_description, "\n"),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''
