#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Manual post-processing. This is mostly just adding tags for things
# that have been moved on the mail host.

# Everything new starts out with +inbox +unread by default. Anything
# that is in a non-inbox folder should be "-inbox +folder" to show up
# in the right places only.

notmuch tag --batch <<EOF
# Archive
-inbox -unread -- path:fastmail/Archive/**
-inbox -unread -- path:"circleci-gmail/[Gmail]/All Mail/**" and not path:"circleci-gmail/Inbox/**"

# Deleted
-inbox -unread +deleted -- path:fastmail/Trash/** or path:"circleci-gmail/[Gmail]/Bin/**"

# Spam
-inbox -unread +spam -- path:fastmail/Spam/** or path "circleci-gmail/[Gmail]/Spam/**"

# Recruiting
-inbox -unread +recruiting -- path:fastmail/Recruitment/**

# Sent
-inbox -unread -draft +sent -- path:fastmail/Sent/** or path:"circleci-gmail/[Gmail]/Sent Mail/**"

# Drafts
# -unread -- tag:draft

# CircleCI
+circleci -- path:circleci-gmail/**

# GitHub
+github -- from:notifications@github.com
+github +resolved -- from:notifications@github.com and ("^Merged #" or "^Closed #")

# Atlassian
+jira -- from:jira@circleci.atlassian.net
+confluence -- from:confluence@circleci.atlassian.net

# Gmail filters
-unread -inbox +calendar -- path:circleci-gmail/Calendar/**
-unread -inbox +rollbar -- path:circleci-gmail/Rollbar/**
-unread -inbox +datadog -- path:circleci-gmail/DataDog/**
-unread -inbox +ops -- path:circleci-gmail/Ops/**
-unread -inbox +oxbot -- path:"circleci-gmail/Ox Bot/**"
EOF
