#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Manual post-processing.
notmuch tag --batch <<EOF
# +inbox the inbox.
# +inbox -- path:fastmail/INBOX/**

# Spam
+spam -- path:fastmail/Spam/**

# +Sent mail.
-inbox -unread -draft +sent -- path:fastmail/Sent/** or path:"circleci-gmail/[Gmail]/Sent Mail/**"

# +draft drafts.
# -unread -- tag:draft

# +circleci my work account.
+circleci -- path:circleci-gmail/**

# +github Github notifications.
+github -- from:notifications@github.com
+github +resolved -- from:notifications@github.com and ("Merged #" or "Closed #")

# +jira JIRA notifications.
+jira -- from:jira@circleci.atlassian.net

# -unread what has been filtered by Gmail already.
-unread -inbox +calendar -- path:circleci-gmail/Calendar/**
-unread -inbox +rollbar -- path:circleci-gmail/Rollbar/**
-unread -inbox +datadog -- path:circleci-gmail/DataDog/**
-unread -inbox +ops -- path:circleci-gmail/Ops/**
-unread -inbox +oxbot -- path:"circleci-gmail/Ox Bot/**"
EOF
