#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Manual post-processing. This is mostly just adding tags for things
# that have been moved on the mail host.

# Everything new starts out with +inbox +unread by default. Anything
# that is in a non-inbox folder should be "-inbox +folder" to show up
# in the right places only.

notmuch tag --batch <<EOF
# Archive
-inbox -unread -- path:fastmail/Archive/**
-inbox -unread -- path:"circleci-gmail/[Gmail]/All Mail/**" and not path:"circleci-gmail/Inbox/**"

# Deleted
-inbox +deleted -- path:fastmail/Trash/** or path:"circleci-gmail/[Gmail]/Bin/**"

# Spam
-inbox +spam -- path:fastmail/Spam/** or path "circleci-gmail/[Gmail]/Spam/**"
-inbox +spam -- tag:circleci and subject:users and /samples?/ and thanks and sendgrid

# Recruiting
-inbox -unread +recruiting -- path:fastmail/Recruitment/**

# Sent
-inbox -unread -draft +sent -- path:fastmail/Sent/** or path:"circleci-gmail/[Gmail]/Sent Mail/**"

# Drafts
# -unread -- tag:draft

# CircleCI
+circleci -- path:circleci-gmail/**

# GitHub
+github -- from:notifications@github.com
+resolved -- tag:github and ("^Merged #" or "^Closed #")

# Atlassian
+jira -- from:jira@circleci.atlassian.net
-inbox -- tag:jira and not ("commented on" or "mentioned you on")
+confluence -- from:confluence@circleci.atlassian.net

# Gmail filters
-inbox +calendar -- path:circleci-gmail/Calendar/**
-inbox +rollbar -- path:circleci-gmail/Rollbar/**
-inbox +datadog -- path:circleci-gmail/DataDog/**
-inbox +ops -- path:circleci-gmail/Ops/**
-inbox +oxbot -- path:"circleci-gmail/Ox Bot/**"
EOF
