#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Delete deleted emails older than 4 weeks.
notmuch search --output=files --format=text0 --exclude=false -- tag:deleted and date:..4w | xargs -0 rm || true

# Delete spam older than 4 weeks.
notmuch search --output=files --format=text0 --exclude=false -- tag:spam and date:..4w | xargs -0 rm || true

# Move to the right folders according to tags.
# Make sure we have updated paths.
# notmuch new --no-hooks

# Fastmail

# Anything to inbox.
# notmuch search --output=files --format=text0 -- folder:fastmail and not folder:fastmail/INBOX and tag:inbox | xargs -0 mv ~/.mail/fastmail/INBOX/new/
# # Archive from inbox.
# notmuch search --output=files --format=text0 -- folder:fastmail/INBOX and not tag:inbox | xargs -0tI {} mv -n {} ~/.mail/fastmail/Archive/new/
# # Spam.
# notmuch search --output=files --format=text0 -- folder:fastmail and not folder:fastmail/Spam and tag:spam | xargs -0tI {} mv -n {} ~/.mail/fastmail/Spam/new/
# # Trash.
# notmuch search --output=files --format=text0 -- folder:fastmail and not folder:fastmail/Trash and tag:deleted | xargs -0tI {} mv -n {} ~/.mail/fastmail/Trash/new/

# CircleCI Gmail
# notmuch search --output=files --format=text0 -- folder:'fastmail' and not folder:fastmail/INBOX and tag:inbox | xargs -0 mv ~/.mail/fastmail/INBOX/new/
# # Archive from inbox.
# notmuch search --output=files --format=text0 -- tag:circleci and path:circleci-gmail/Inbox and not tag:inbox | xargs -0tI {} mv -n {} ~/.mail/fastmail/Archive/new/
# # Spam.
# notmuch search --output=files --format=text0 -- folder:'fastmail' and not folder:'fastmail/Spam' and tag:spam | xargs -0tI {} mv -n {} ~/.mail/fastmail/Spam/new/
# # Trash.
# notmuch search --output=files --format=text0 -- folder:'fastmail' and not folder:'fastmail/Trash' and tag:deleted | xargs -0tI {} mv -n {} ~/.mail/fastmail/Trash/new/

# Make sure we have updated paths.
# notmuch new --no-hooks
