#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Strip UIDs from filenames when moving mails so that mbsync doesn't
# get confused.
mv_without_uid () {
    while IFS= read -r name; do
        new_name="$(basename $name | awk -F ',' '{print $1}')"
        target="$1"
        mv -n "$name" "$1/new/$new_name"
    done
}

# Delete deleted emails older than 4 weeks.
notmuch search --output=files --format=text0 --exclude=false -- tag:deleted and date:..4w | xargs -0 rm || true

# Delete spam older than 4 weeks.
notmuch search --output=files --format=text0 --exclude=false -- tag:spam and date:..4w | xargs -0 rm || true

# Move to the right folders according to tags, so that other mail
# clients don't just have a gigantic inbox.

# Make sure we have updated paths.
notmuch new --no-hooks

# Fastmail

# Trash.
notmuch search --output=files -- path:"fastmail/INBOX/**" and tag:deleted | mv_without_uid ~/.mail/fastmail/Trash
# Spam.
notmuch search --output=files -- path:"fastmail/INBOX/**" tag:spam | mv_without_uid ~/.mail/fastmail/Spam
# Recruiter email.
notmuch search --output=files -- path:"fastmail/INBOX/**" and tag:recruiting | mv_without_uid ~/.mail/fastmail/Recruitment
# Archive from inbox.
notmuch search --output=files -- path:"fastmail/INBOX/**" and not tag:inbox | mv_without_uid ~/.mail/fastmail/Archive

# CircleCI Gmail

# Spam.
notmuch search --output=files -- path:"circleci-gmail/Inbox/**" tag:spam | mv_without_uid ~/.mail/circleci-gmail/\[Gmail\]/Spam
# Trash.
notmuch search --output=files -- path:"circleci-gmail/Inbox/**" and tag:deleted | mv_without_uid ~/.mail/circleci-gmail/\[Gmail\]/Bin
# The various tags.
notmuch search --output=files -- path:"circleci-gmail/Inbox/**" and tag:calendar | mv_without_uid ~/.mail/circleci-gmail/Calendar
notmuch search --output=files -- path:"circleci-gmail/Inbox/**" and tag:datadog | mv_without_uid ~/.mail/circleci-gmail/DataDog
notmuch search --output=files -- path:"circleci-gmail/Inbox/**" and tag:ops | mv_without_uid ~/.mail/circleci-gmail/Ops
notmuch search --output=files -- path:"circleci-gmail/Inbox/**" and tag:oxbot | mv_without_uid ~/.mail/circleci-gmail/Ox\ Bot
notmuch search --output=files -- path:"circleci-gmail/Inbox/**" and tag:rollbar | mv_without_uid ~/.mail/circleci-gmail/Rollbar
# Archive from inbox.
notmuch search --output=files -- path:"circleci-gmail/Inbox/**" and not tag:inbox | mv_without_uid ~/.mail/circleci-gmail/\[Gmail\]/All\ Mail

# Make sure we have updated paths.
notmuch new --no-hooks
