#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Delete deleted emails older than 4 weeks.
notmuch search --output=files --format=text0 --exclude=false -- tag:deleted and date:..4w | xargs -0 rm || true

# Delete spam older than 4 weeks.
notmuch search --output=files --format=text0 --exclude=false -- tag:spam and date:..4w | xargs -0 rm || true